import { ref, computed } from 'vue'
import { defineStore } from 'pinia'

export const useAuthStore = defineStore('auth', () => {
  // States
  const user = ref({})

  const tokens = [
    {
      id: '3',
      network_id: '1',
      network_identifier: '1',
      address: '__BASE_TOKEN__',
      name: 'Tron',
      symbol: 'TRX',
      decimals: '6',
      logo: null,
      status: '1',
      is_custom: '0',
      created_at: '2022-11-10 19:29:24',
      updated_at: null,
      network: {
        id: '1',
        chain_type: 'trx',
        nick_name: 'tron',
        name: 'Tron',
        api_url: 'https://api.trongrid.io',
        explorer_address:
          '{\n"contract":"https://tronscan.io/#/contract/",\n"wallet":"https://tronscan.io/#/address/",\n"hash":"https://tronscan.io/#/transaction/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '32',
      network_id: '1',
      network_identifier: '2',
      address: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
      name: 'Tether USD',
      symbol: 'USDT',
      decimals: '6',
      logo: '/icons/32/color/usdt.png',
      status: '1',
      is_custom: '0',
      created_at: '2022-12-14 09:14:07',
      updated_at: null,
      network: {
        id: '1',
        chain_type: 'trx',
        nick_name: 'tron',
        name: 'Tron',
        api_url: 'https://api.trongrid.io',
        explorer_address:
          '{\n"contract":"https://tronscan.io/#/contract/",\n"wallet":"https://tronscan.io/#/address/",\n"hash":"https://tronscan.io/#/transaction/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '1',
      network_id: '2',
      network_identifier: '1',
      address: '__BASE_TOKEN__',
      name: 'Ethereum',
      symbol: 'ETH',
      decimals: '18',
      logo: null,
      status: '1',
      is_custom: '0',
      created_at: '2022-11-10 19:29:24',
      updated_at: null,
      network: {
        id: '2',
        chain_type: 'eth',
        nick_name: 'ethereum',
        name: 'Ethereum',
        api_url: 'https://eth-mainnet.g.alchemy.com/v2/cJCj-yw33cuZacdqlHHUkQoTEh_Lxevh',
        explorer_address:
          '{\n"contract":"https://etherscan.io/token/",\n"wallet":"https://etherscan.io/address/",\n"hash":"https://etherscan.io/tx/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '28',
      network_id: '2',
      network_identifier: '4',
      address: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
      name: 'Uniswap',
      symbol: 'UNI',
      decimals: '6',
      logo: '/icons/32/color/uni.png',
      status: '1',
      is_custom: '0',
      created_at: '2022-11-15 16:27:01',
      updated_at: null,
      network: {
        id: '2',
        chain_type: 'eth',
        nick_name: 'ethereum',
        name: 'Ethereum',
        api_url: 'https://eth-mainnet.g.alchemy.com/v2/cJCj-yw33cuZacdqlHHUkQoTEh_Lxevh',
        explorer_address:
          '{\n"contract":"https://etherscan.io/token/",\n"wallet":"https://etherscan.io/address/",\n"hash":"https://etherscan.io/tx/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '29',
      network_id: '2',
      network_identifier: '5',
      address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
      name: 'USD Coin',
      symbol: 'USDC',
      decimals: '6',
      logo: '/icons/32/color/usdc.png',
      status: '1',
      is_custom: '0',
      created_at: '2022-11-17 19:49:19',
      updated_at: null,
      network: {
        id: '2',
        chain_type: 'eth',
        nick_name: 'ethereum',
        name: 'Ethereum',
        api_url: 'https://eth-mainnet.g.alchemy.com/v2/cJCj-yw33cuZacdqlHHUkQoTEh_Lxevh',
        explorer_address:
          '{\n"contract":"https://etherscan.io/token/",\n"wallet":"https://etherscan.io/address/",\n"hash":"https://etherscan.io/tx/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '34',
      network_id: '2',
      network_identifier: '6',
      address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
      name: 'Tether USD',
      symbol: 'USDT',
      decimals: '6',
      logo: '/icons/32/color/usdt.png',
      status: '1',
      is_custom: '0',
      created_at: '2022-12-14 09:15:49',
      updated_at: null,
      network: {
        id: '2',
        chain_type: 'eth',
        nick_name: 'ethereum',
        name: 'Ethereum',
        api_url: 'https://eth-mainnet.g.alchemy.com/v2/cJCj-yw33cuZacdqlHHUkQoTEh_Lxevh',
        explorer_address:
          '{\n"contract":"https://etherscan.io/token/",\n"wallet":"https://etherscan.io/address/",\n"hash":"https://etherscan.io/tx/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '7',
      network_id: '3',
      network_identifier: '1',
      address: '__BASE_TOKEN__',
      name: 'Binance Chain',
      symbol: 'BNB',
      decimals: '18',
      logo: null,
      status: '1',
      is_custom: '0',
      created_at: '2022-11-10 19:29:24',
      updated_at: null,
      network: {
        id: '3',
        chain_type: 'eth',
        nick_name: 'binance',
        name: 'Binance Chain',
        api_url: 'https://bsc-dataseed.binance.org/',
        explorer_address: '',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '35',
      network_id: '3',
      network_identifier: '2',
      address: '0x55d398326f99059fF775485246999027B3197955',
      name: 'Tether USD',
      symbol: 'USDT',
      decimals: '6',
      logo: '/icons/32/color/usdt.png',
      status: '1',
      is_custom: '0',
      created_at: '2022-12-14 09:17:15',
      updated_at: null,
      network: {
        id: '3',
        chain_type: 'eth',
        nick_name: 'binance',
        name: 'Binance Chain',
        api_url: 'https://bsc-dataseed.binance.org/',
        explorer_address: '',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '5',
      network_id: '4',
      network_identifier: '1',
      address: '__BASE_TOKEN__',
      name: 'Matic',
      symbol: 'Matic',
      decimals: '18',
      logo: null,
      status: '1',
      is_custom: '0',
      created_at: '2022-11-10 19:29:24',
      updated_at: null,
      network: {
        id: '4',
        chain_type: 'eth',
        nick_name: 'polygon',
        name: 'Polygon',
        api_url: 'https://polygon-mainnet.g.alchemy.com/v2/pKS9h8AzqMmkcaAqW0Lo7RrrBfQPqgq8',
        explorer_address:
          '{\n"contract":"https://polygonscan.com/token/",\n"wallet":"https://polygonscan.com/address/",\n"hash":"https://polygonscan.com/tx/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '30',
      network_id: '4',
      network_identifier: '2',
      address: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
      name: 'USD Coin (PoS)',
      symbol: 'USDC',
      decimals: '6',
      logo: '/icons/32/color/usdc.png',
      status: '1',
      is_custom: '0',
      created_at: '2022-11-17 19:50:30',
      updated_at: null,
      network: {
        id: '4',
        chain_type: 'eth',
        nick_name: 'polygon',
        name: 'Polygon',
        api_url: 'https://polygon-mainnet.g.alchemy.com/v2/pKS9h8AzqMmkcaAqW0Lo7RrrBfQPqgq8',
        explorer_address:
          '{\n"contract":"https://polygonscan.com/token/",\n"wallet":"https://polygonscan.com/address/",\n"hash":"https://polygonscan.com/tx/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '33',
      network_id: '4',
      network_identifier: '3',
      address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
      name: 'Tether USD',
      symbol: 'USDT',
      decimals: '6',
      logo: '/icons/32/color/usdt.png',
      status: '1',
      is_custom: '0',
      created_at: '2022-12-14 09:14:50',
      updated_at: null,
      network: {
        id: '4',
        chain_type: 'eth',
        nick_name: 'polygon',
        name: 'Polygon',
        api_url: 'https://polygon-mainnet.g.alchemy.com/v2/pKS9h8AzqMmkcaAqW0Lo7RrrBfQPqgq8',
        explorer_address:
          '{\n"contract":"https://polygonscan.com/token/",\n"wallet":"https://polygonscan.com/address/",\n"hash":"https://polygonscan.com/tx/"\n}',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '11',
      network_id: '9',
      network_identifier: '1',
      address: '__BASE_TOKEN__',
      name: 'BitCoin',
      symbol: 'BTC',
      decimals: '18',
      logo: null,
      status: '1',
      is_custom: '0',
      created_at: '2022-11-10 19:29:24',
      updated_at: null,
      network: {
        id: '9',
        chain_type: 'btc',
        nick_name: 'bitcoin',
        name: 'BitCoin',
        api_url: '',
        explorer_address: '',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '13',
      network_id: '13',
      network_identifier: '1',
      address: '__BASE_TOKEN__',
      name: 'LiteCoin',
      symbol: 'LTC',
      decimals: '18',
      logo: null,
      status: '1',
      is_custom: '0',
      created_at: '2022-11-10 19:29:24',
      updated_at: null,
      network: {
        id: '13',
        chain_type: 'ltc',
        nick_name: 'litecoin',
        name: 'LiteCoin',
        api_url: '',
        explorer_address: '',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    },
    {
      id: '14',
      network_id: '14',
      network_identifier: '1',
      address: '__BASE_TOKEN__',
      name: 'DogeCoin',
      symbol: 'DOGE',
      decimals: '18',
      logo: null,
      status: '1',
      is_custom: '0',
      created_at: '2022-11-10 19:29:24',
      updated_at: null,
      network: {
        id: '14',
        chain_type: 'doge',
        nick_name: 'dogecoin',
        name: 'DogeCoin',
        api_url: '',
        explorer_address: '',
        base_token_id: '0',
        is_mainnnet: '1',
        status: '1',
        expire_in: '3600',
        withdraw_static_usd_fee: '1.00',
        withdraw_percent_fee: '0.00',
        created_at: '2023-08-05 12:19:21',
        updated_at: null
      }
    }
  ]

  const networks = [
    {
      id: '1',
      chain_type: 'trx',
      nick_name: 'tron',
      name: 'Tron',
      api_url: 'https://api.trongrid.io',
      explorer_address:
        '{\n"contract":"https://tronscan.io/#/contract/",\n"wallet":"https://tronscan.io/#/address/",\n"hash":"https://tronscan.io/#/transaction/"\n}',
      base_token_id: '0',
      is_mainnnet: '1',
      status: '1',
      expire_in: '3600',
      withdraw_static_usd_fee: '1.00',
      withdraw_percent_fee: '0.00',
      created_at: '2023-08-05 12:19:21',
      updated_at: null,
      tokens: [
        {
          id: '3',
          network_id: '1',
          network_identifier: '1',
          address: '__BASE_TOKEN__',
          name: 'Tron',
          symbol: 'TRX',
          decimals: '6',
          logo: null,
          status: '1',
          is_custom: '0',
          created_at: '2022-11-10 19:29:24',
          updated_at: null
        },
        {
          id: '32',
          network_id: '1',
          network_identifier: '2',
          address: 'TR7NHqjeKQxGTCi8q8ZY4pL8otSzgjLj6t',
          name: 'Tether USD',
          symbol: 'USDT',
          decimals: '6',
          logo: '/icons/32/color/usdt.png',
          status: '1',
          is_custom: '0',
          created_at: '2022-12-14 09:14:07',
          updated_at: null
        }
      ],
      symbol: 'TRX'
    },
    {
      id: '2',
      chain_type: 'eth',
      nick_name: 'ethereum',
      name: 'Ethereum',
      api_url: 'https://eth-mainnet.g.alchemy.com/v2/cJCj-yw33cuZacdqlHHUkQoTEh_Lxevh',
      explorer_address:
        '{\n"contract":"https://etherscan.io/token/",\n"wallet":"https://etherscan.io/address/",\n"hash":"https://etherscan.io/tx/"\n}',
      base_token_id: '0',
      is_mainnnet: '1',
      status: '1',
      expire_in: '3600',
      withdraw_static_usd_fee: '1.00',
      withdraw_percent_fee: '0.00',
      created_at: '2023-08-05 12:19:21',
      updated_at: null,
      tokens: [
        {
          id: '1',
          network_id: '2',
          network_identifier: '1',
          address: '__BASE_TOKEN__',
          name: 'Ethereum',
          symbol: 'ETH',
          decimals: '18',
          logo: null,
          status: '1',
          is_custom: '0',
          created_at: '2022-11-10 19:29:24',
          updated_at: null
        },
        {
          id: '28',
          network_id: '2',
          network_identifier: '4',
          address: '0x1f9840a85d5af5bf1d1762f925bdaddc4201f984',
          name: 'Uniswap',
          symbol: 'UNI',
          decimals: '6',
          logo: '/icons/32/color/uni.png',
          status: '1',
          is_custom: '0',
          created_at: '2022-11-15 16:27:01',
          updated_at: null
        },
        {
          id: '29',
          network_id: '2',
          network_identifier: '5',
          address: '0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48',
          name: 'USD Coin',
          symbol: 'USDC',
          decimals: '6',
          logo: '/icons/32/color/usdc.png',
          status: '1',
          is_custom: '0',
          created_at: '2022-11-17 19:49:19',
          updated_at: null
        },
        {
          id: '31',
          network_id: '2',
          network_identifier: '2',
          address: '0x4d224452801aced8b2f0aebe155379bb5d594381',
          name: 'ApeCoin',
          symbol: 'APE',
          decimals: '6',
          logo: '/icons/32/color/ape.png',
          status: '1',
          is_custom: '1',
          created_at: '2022-11-26 16:50:47',
          updated_at: null
        },
        {
          id: '34',
          network_id: '2',
          network_identifier: '6',
          address: '0xdac17f958d2ee523a2206206994597c13d831ec7',
          name: 'Tether USD',
          symbol: 'USDT',
          decimals: '6',
          logo: '/icons/32/color/usdt.png',
          status: '1',
          is_custom: '0',
          created_at: '2022-12-14 09:15:49',
          updated_at: null
        }
      ],
      symbol: 'ETH'
    },
    {
      id: '3',
      chain_type: 'eth',
      nick_name: 'binance',
      name: 'Binance Chain',
      api_url: 'https://bsc-dataseed.binance.org/',
      explorer_address: '',
      base_token_id: '0',
      is_mainnnet: '1',
      status: '1',
      expire_in: '3600',
      withdraw_static_usd_fee: '1.00',
      withdraw_percent_fee: '0.00',
      created_at: '2023-08-05 12:19:21',
      updated_at: null,
      tokens: [
        {
          id: '7',
          network_id: '3',
          network_identifier: '1',
          address: '__BASE_TOKEN__',
          name: 'Binance Chain',
          symbol: 'BNB',
          decimals: '18',
          logo: null,
          status: '1',
          is_custom: '0',
          created_at: '2022-11-10 19:29:24',
          updated_at: null
        },
        {
          id: '35',
          network_id: '3',
          network_identifier: '2',
          address: '0x55d398326f99059fF775485246999027B3197955',
          name: 'Tether USD',
          symbol: 'USDT',
          decimals: '6',
          logo: '/icons/32/color/usdt.png',
          status: '1',
          is_custom: '0',
          created_at: '2022-12-14 09:17:15',
          updated_at: null
        }
      ],
      symbol: 'BNB'
    },
    {
      id: '4',
      chain_type: 'eth',
      nick_name: 'polygon',
      name: 'Polygon',
      api_url: 'https://polygon-mainnet.g.alchemy.com/v2/pKS9h8AzqMmkcaAqW0Lo7RrrBfQPqgq8',
      explorer_address:
        '{\n"contract":"https://polygonscan.com/token/",\n"wallet":"https://polygonscan.com/address/",\n"hash":"https://polygonscan.com/tx/"\n}',
      base_token_id: '0',
      is_mainnnet: '1',
      status: '1',
      expire_in: '3600',
      withdraw_static_usd_fee: '1.00',
      withdraw_percent_fee: '0.00',
      created_at: '2023-08-05 12:19:21',
      updated_at: null,
      tokens: [
        {
          id: '5',
          network_id: '4',
          network_identifier: '1',
          address: '__BASE_TOKEN__',
          name: 'Matic',
          symbol: 'Matic',
          decimals: '18',
          logo: null,
          status: '1',
          is_custom: '0',
          created_at: '2022-11-10 19:29:24',
          updated_at: null
        },
        {
          id: '30',
          network_id: '4',
          network_identifier: '2',
          address: '0x2791Bca1f2de4661ED88A30C99A7a9449Aa84174',
          name: 'USD Coin (PoS)',
          symbol: 'USDC',
          decimals: '6',
          logo: '/icons/32/color/usdc.png',
          status: '1',
          is_custom: '0',
          created_at: '2022-11-17 19:50:30',
          updated_at: null
        },
        {
          id: '33',
          network_id: '4',
          network_identifier: '3',
          address: '0xc2132D05D31c914a87C6611C10748AEb04B58e8F',
          name: 'Tether USD',
          symbol: 'USDT',
          decimals: '6',
          logo: '/icons/32/color/usdt.png',
          status: '1',
          is_custom: '0',
          created_at: '2022-12-14 09:14:50',
          updated_at: null
        },
        {
          id: '36',
          network_id: '4',
          network_identifier: '4',
          address: '0x11340ed6535D64780D2900d410d09Acf8315E233',
          name: 'Alen Trades',
          symbol: 'ALN',
          decimals: '6',
          logo: '/icons/default.png',
          status: '1',
          is_custom: '1',
          created_at: '2023-01-08 13:57:09',
          updated_at: null
        },
        {
          id: '37',
          network_id: '4',
          network_identifier: '5',
          address: '0x3050731a7Ab18D05eAa5E01D66DF33E04444e72c',
          name: 'ECS GOLD',
          symbol: 'ECG',
          decimals: '6',
          logo: '/icons/32/color/ecg.png',
          status: '1',
          is_custom: '1',
          created_at: '2023-01-08 14:15:03',
          updated_at: null
        }
      ],
      symbol: 'Matic'
    },
    {
      id: '9',
      chain_type: 'btc',
      nick_name: 'bitcoin',
      name: 'BitCoin',
      api_url: '',
      explorer_address: '',
      base_token_id: '0',
      is_mainnnet: '1',
      status: '1',
      expire_in: '3600',
      withdraw_static_usd_fee: '1.00',
      withdraw_percent_fee: '0.00',
      created_at: '2023-08-05 12:19:21',
      updated_at: null,
      tokens: [
        {
          id: '11',
          network_id: '9',
          network_identifier: '1',
          address: '__BASE_TOKEN__',
          name: 'BitCoin',
          symbol: 'BTC',
          decimals: '18',
          logo: null,
          status: '1',
          is_custom: '0',
          created_at: '2022-11-10 19:29:24',
          updated_at: null
        }
      ],
      symbol: 'BTC'
    },
    {
      id: '13',
      chain_type: 'ltc',
      nick_name: 'litecoin',
      name: 'LiteCoin',
      api_url: '',
      explorer_address: '',
      base_token_id: '0',
      is_mainnnet: '1',
      status: '1',
      expire_in: '3600',
      withdraw_static_usd_fee: '1.00',
      withdraw_percent_fee: '0.00',
      created_at: '2023-08-05 12:19:21',
      updated_at: null,
      tokens: [
        {
          id: '13',
          network_id: '13',
          network_identifier: '1',
          address: '__BASE_TOKEN__',
          name: 'LiteCoin',
          symbol: 'LTC',
          decimals: '18',
          logo: null,
          status: '1',
          is_custom: '0',
          created_at: '2022-11-10 19:29:24',
          updated_at: null
        }
      ],
      symbol: 'LTC'
    },
    {
      id: '14',
      chain_type: 'doge',
      nick_name: 'dogecoin',
      name: 'DogeCoin',
      api_url: '',
      explorer_address: '',
      base_token_id: '0',
      is_mainnnet: '1',
      status: '1',
      expire_in: '3600',
      withdraw_static_usd_fee: '1.00',
      withdraw_percent_fee: '0.00',
      created_at: '2023-08-05 12:19:21',
      updated_at: null,
      tokens: [
        {
          id: '14',
          network_id: '14',
          network_identifier: '1',
          address: '__BASE_TOKEN__',
          name: 'DogeCoin',
          symbol: 'DOGE',
          decimals: '18',
          logo: null,
          status: '1',
          is_custom: '0',
          created_at: '2022-11-10 19:29:24',
          updated_at: null
        }
      ],
      symbol: 'DOGE'
    }
  ]

  // Getters

  // Function
  const doubleCount = computed(() => count.value * 2)
  function increment() {
    count.value++
  }

  return { doubleCount, increment, tokens, networks }
})
